FROM node:22-alpine
WORKDIR /app
COPY frontend-v2/package*.json ./frontend-v2/
RUN npm --prefix frontend-v2 install
COPY frontend-v2 ./frontend-v2
WORKDIR /app/frontend-v2
EXPOSE 3000
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","3000"]
