const base=process.env.NEXTESS_API_BASE||'http://localhost:4000';
const unique=Date.now().toString(36);
const cookieOf=(response)=>response.headers.get('set-cookie')?.split(';')[0]||'';
const request=async(path,init={})=>{const response=await fetch(base+path,init);const body=await response.json().catch(()=>({}));return {response,body};};
const expect=(condition,message)=>{if(!condition)throw new Error(message);};
const subjects=await request('/v1/subjects');
expect(subjects.response.ok,'subjects endpoint failed');
expect(subjects.body.subjects?.some(s=>s.status==='ACTIVE'),'no active subject returned');
expect(subjects.body.subjects?.some(s=>s.status==='FUTURE'),'future subject catalogue is missing');
const physics=subjects.body.subjects.find(s=>s.key.toLowerCase()==='physics');
expect(physics,'Physics subject is missing');
const catalogue=await request('/v1/subjects/'+physics.id+'/projects');
expect(catalogue.response.ok&&catalogue.body.projects?.length>0,'published mission catalogue failed');
const project=catalogue.body.projects[0];
const detail=await request('/v1/projects/'+project.id);
expect(detail.response.ok,'project detail failed');
expect(detail.body.project.currentPublishedVersion?.id===project.currentPublishedVersion?.id,'published version mismatch');
const register=async(name)=>{const result=await request('/v1/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,username:name,password:'NextessSmoke123',profileType:'STUDENT'})});expect(result.response.ok,'smoke registration failed');const cookie=cookieOf(result.response);expect(cookie,'registration did not establish a session cookie');return cookie;};
const cookieA=await register('smoke-a-'+unique);
const start=await request('/v1/projects/'+project.id+'/start',{method:'POST',headers:{Cookie:cookieA}});
expect(start.response.ok&&start.body.investigationId,'mission start failed');
const investigation=await request('/v1/investigations/'+start.body.investigationId,{headers:{Cookie:cookieA}});
expect(investigation.response.ok,'investigation retrieval failed');
const firstQuestion=investigation.body.investigation?.projectVersion?.levels?.[0]?.questions?.[0];
expect(firstQuestion,'published mission has no first question');
const answer=firstQuestion.questionType==='numerical'?0:(firstQuestion.options?.[0]?.optionText??'');
expect(String(answer).length>0,'first question has no testable input');
const key='smoke-'+unique;
const init={method:'POST',headers:{'Content-Type':'application/json','Cookie':cookieA,'Idempotency-Key':key},body:JSON.stringify({questionId:firstQuestion.id,answer:{value:answer}})};
const first=await request('/v1/investigations/'+start.body.investigationId+'/answers',init);
expect(first.response.ok&&['CORRECT','INCORRECT'].includes(first.body.result),'answer evaluation failed');
const replay=await request('/v1/investigations/'+start.body.investigationId+'/answers',init);
expect(replay.response.ok&&replay.body.replayed===true,'answer retry was not idempotent');
const concurrent=await Promise.all([request('/v1/investigations/'+start.body.investigationId+'/answers',init),request('/v1/investigations/'+start.body.investigationId+'/answers',init)]);
expect(concurrent.every(x=>x.response.ok),'concurrent idempotent submissions failed');
expect(new Set(concurrent.map(x=>x.body.answerId)).size===1,'concurrent idempotent submissions created multiple answers');
expect(replay.body.answerId===first.body.answerId,'answer retry created another answer');
const secondProject=catalogue.body.projects.find(p=>p.id!==project.id);
if(secondProject){
  const secondStart=await request('/v1/projects/'+secondProject.id+'/start',{method:'POST',headers:{Cookie:cookieA}});
  expect(secondStart.response.ok&&secondStart.body.investigationId,'second mission start failed');
  const secondInvestigation=await request('/v1/investigations/'+secondStart.body.investigationId,{headers:{Cookie:cookieA}});
  const secondQuestion=secondInvestigation.body.investigation?.projectVersion?.levels?.[0]?.questions?.[0];
  expect(secondQuestion,'second mission has no first question');
  const secondAnswer=secondQuestion.questionType==='numerical'?0:(secondQuestion.options?.[0]?.optionText??'');
  const second=await request('/v1/investigations/'+secondStart.body.investigationId+'/answers',{method:'POST',headers:{'Content-Type':'application/json','Cookie':cookieA,'Idempotency-Key':key},body:JSON.stringify({questionId:secondQuestion.id,answer:{value:secondAnswer}})});
  expect(second.response.ok,'same idempotency key was incorrectly shared across investigations');
  expect(second.body.answerId!==first.body.answerId,'idempotency key leaked across investigations');
}
const malformed=await request('/v1/investigations/not-a-uuid/answers',{method:'POST',headers:{'Content-Type':'application/json','Cookie':cookieA,'Idempotency-Key':'bad-input'},body:JSON.stringify({questionId:'bad',answer:{value:'x'}})});
expect(malformed.response.status===400&&malformed.body.error?.code==='VALIDATION_ERROR','invalid investigation IDs are not validated consistently');
const cookieB=await register('smoke-b-'+unique);
const cross=await request('/v1/investigations/'+start.body.investigationId,{headers:{Cookie:cookieB}});
expect(cross.response.status===404,'cross-user investigation access was not rejected');
console.log(JSON.stringify({ok:true,mission:project.slug,replayed:true,crossUserRejected:true}));
