import React from 'react';
import { ActivePage, ThemeMode, UserStats } from '../types';

interface ProfileViewProps { theme: ThemeMode; stats: UserStats; onNavigate: (page: ActivePage) => void; onOpenEditProfile: () => void; onShowToast: (msg: string) => void; onToggleGuest?: () => void; badges?: Array<{badge:{name:string;description:string;kind:string};earnedAt:string}>; }

export const ProfileView: React.FC<ProfileViewProps> = ({ theme, stats, onNavigate, onOpenEditProfile, onToggleGuest, badges = [] }) => {
  const isDark = theme === 'dark';
  return (
    <div className="flex flex-col w-full pb-20">
      <section className={isDark ? 'w-full rounded-2xl p-6 shadow-xl relative overflow-hidden border mb-6 bg-[#12131b] border-violet-500/25' : 'w-full rounded-2xl p-6 shadow-xl relative overflow-hidden border mb-6 bg-gradient-to-br from-purple-50/90 via-white to-violet-50/70 border-violet-200'}>
        <div className="relative z-10 flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-5"><div className="w-28 h-28 sm:w-32 sm:h-32 rounded-2xl bg-[#1e1f29] border border-violet-500/30 flex items-center justify-center shadow-[0_0_24px_rgba(167,139,250,0.25)]"><span className="material-symbols-outlined text-[54px] text-violet-400">account_circle</span></div><div className="flex flex-col gap-1"><div className="flex flex-wrap items-center gap-2.5"><h1 className={isDark ? 'font-headline-lg text-2xl md:text-3xl font-bold text-white' : 'font-headline-lg text-2xl md:text-3xl font-bold text-slate-900'}>{stats.name}</h1>{stats.handle && <span className="px-2.5 py-0.5 rounded-full bg-violet-600/20 border border-violet-500/30 text-violet-300 font-mono text-xs">{stats.handle}</span>}</div><div className="flex flex-wrap items-center gap-2 mt-1"><span className="font-mono text-xs text-violet-400 font-semibold">{stats.profession || (stats.isGuest ? 'Explorer Guest' : 'Nextess Learner')}</span>{stats.college && <><span className="text-slate-500">•</span><span className="text-xs text-slate-400">{stats.college}</span></>}{stats.userClass && <><span className="text-slate-500">•</span><span className="font-mono text-xs px-2 py-0.5 rounded bg-violet-500/10 text-violet-300 border border-violet-500/20">{stats.userClass}</span></>}</div></div></div>
          <div className="flex sm:flex-row lg:flex-col gap-2"><button onClick={onOpenEditProfile} className="px-5 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-semibold text-xs">Edit Profile</button>{onToggleGuest && <button onClick={onToggleGuest} className={isDark ? 'px-4 py-2 rounded-xl border text-xs font-semibold bg-[#181926] border-violet-500/20 text-slate-300' : 'px-4 py-2 rounded-xl border text-xs font-semibold bg-white border-slate-200 text-slate-700'}>{stats.isGuest ? 'Log In' : 'Switch to Guest Mode'}</button>}</div>
        </div>
      </section>
      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        {[['Knowledge Points',stats.kp.toLocaleString(),'KP','bolt'],['Credits',stats.coins.toLocaleString(),'Coins','monetization_on'],['Current Streak',String(stats.streakDays),'Days Active','local_fire_department'],['Level',String(stats.level),'Current Level','verified']].map(([label,value,unit,icon]) => <div key={label} className={isDark ? 'rounded-2xl p-4 flex flex-col justify-between gap-3 border shadow-sm bg-[#12131b] border-violet-500/15' : 'rounded-2xl p-4 flex flex-col justify-between gap-3 border shadow-sm bg-white border-slate-200'}><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-slate-400 uppercase tracking-wider font-semibold">{label}</span><span className="material-symbols-outlined text-violet-400 text-[18px]">{icon}</span></div><div><span className="font-mono text-xl font-bold">{value}</span><span className="font-mono text-xs text-slate-400 ml-1">{unit}</span></div></div>)}
      </section>
      <section className={isDark ? 'rounded-2xl p-6 border shadow-xl bg-[#12131b] border-violet-500/20' : 'rounded-2xl p-6 border shadow-xl bg-white border-slate-200'}>
        <div className="flex items-center justify-between mb-4"><div><span className="font-mono text-[10px] text-violet-400 uppercase">Server-recorded achievements</span><h2 className="text-lg font-bold mt-1">Badges</h2></div><span className="text-xs text-slate-400">{badges.length} earned</span></div>
        {badges.length ? <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{badges.map((item:any) => <div key={item.badge?.name + item.earnedAt} className={isDark ? 'p-4 rounded-xl border bg-[#181926] border-violet-500/15' : 'p-4 rounded-xl border bg-slate-50 border-slate-200'}><div className="flex items-center gap-2"><span className="material-symbols-outlined text-amber-400">workspace_premium</span><span className="font-semibold text-sm">{item.badge?.name}</span></div><p className="text-xs text-slate-400 mt-2">{item.badge?.description}</p></div>)}</div> : <div className="p-6 rounded-xl border border-dashed border-slate-500/30 text-center text-xs text-slate-400">No earned badges are recorded for this account yet.</div>}
      </section>
    </div>
  );
};